<!DOCTYPE HTML>
<html>
<head>
<!-- Generated by MyLinks XE -->
<title>My Bookmarks</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
*,
*:before,
*:after {
	-webkit-box-sizing: border-box;
	-moz-box-sizing: border-box;
	box-sizing: border-box;
}
html,body{
	padding: 0;
	margin: 0;
	font-size: 1rem;
	line-height: 1.5;
	color: #111;
	font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;

    box-sizing: border-box;
}
html{
	-ms-text-size-adjust: 100%;
  	-webkit-text-size-adjust: 100%;
}
a{
	color: DodgerBlue;
	background-color: transparent;
	text-decoration: none;
}
h1,.h1 {
 font-size:2rem;
}
h2,.h2 {
 font-size:1.5rem;
}
h3,.h3 {
 font-size:1.25rem;
}
h4,.h4 {
 font-size:1rem;
}
h5,.h5 {
 font-size:.875rem;
}
h6,.h6 {
 font-size:.75rem;
 margin: 0;
}

h2{
margin:0px;
padding:px;
}

.wrapper {
	margin: auto;
	padding: 0 1rem;
	max-width: 64rem;
	width: 100%;
}

.wrapper-lg{
	max-width: 960px;
}

a{
padding-left:8px;
}

.info{
padding-left:8px;
font-size:13px;
color:#444;
}


a{text-decoration: none;}
a:hover{color: blue;}
a{display:block;font-size:1rem;}
hr { display: block; height: 1px;border: 0; border-top: 1px solid #ccc;margin: 1em 0; padding: 0; }
</style>
</head>
<body>
<h1 style="text-align:center">Bookmarks</h1>
<hr>
<div class="wrapper wrapper-lg">
   %BOOKMARK_DATA%
</div>
</body>
</html>
