<!DOCTYPE HTML>
<html>
<head>
<!-- Generated by MyLinks XE -->
<title>%TITLE%</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body,html{font-family: Verdana, Geneva, sans-serif;line-height:1.5;}
a{color: #222;}
a{text-decoration: none;}
a:hover{color: blue;}
a{display:block;font-size:1rem;}
hr { display: block; height: 1px;border: 0; border-top: 1px solid #ccc;margin: 1em 0; padding: 0; }
</style>
</head>
<body>
<h1>%TITLE%</h1>
<hr>
%LINKS_DATA%
</body>
</html>
